# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

create_graph_rcpp <- function(nvertices, src, dst) {
    .Call('_fastnetworklib_create_graph_rcpp', PACKAGE = 'fastnetworklib', nvertices, src, dst)
}

free_graph_rcpp <- function(graphid) {
    invisible(.Call('_fastnetworklib_free_graph_rcpp', PACKAGE = 'fastnetworklib', graphid))
}

free_all_graphs_rcpp <- function() {
    invisible(.Call('_fastnetworklib_free_all_graphs_rcpp', PACKAGE = 'fastnetworklib'))
}

connected_components_rcpp <- function(graphid) {
    .Call('_fastnetworklib_connected_components_rcpp', PACKAGE = 'fastnetworklib', graphid)
}

