# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

create_graph_rcpp <- function(nvertices, src, dst) {
    .Call('_fastnetworklib_create_graph_rcpp', PACKAGE = 'fastnetworklib', nvertices, src, dst)
}

create_graphw_rcpp <- function(nvertices, src, dst, weights) {
    .Call('_fastnetworklib_create_graphw_rcpp', PACKAGE = 'fastnetworklib', nvertices, src, dst, weights)
}

add_edges_rcpp <- function(graphid, src, dst) {
    .Call('_fastnetworklib_add_edges_rcpp', PACKAGE = 'fastnetworklib', graphid, src, dst)
}

add_edgesw_rcpp <- function(graphid, src, dst, weights) {
    .Call('_fastnetworklib_add_edgesw_rcpp', PACKAGE = 'fastnetworklib', graphid, src, dst, weights)
}

add_edgesl_rcpp <- function(graphid, src, dst, n_weights, n_layer) {
    .Call('_fastnetworklib_add_edgesl_rcpp', PACKAGE = 'fastnetworklib', graphid, src, dst, n_weights, n_layer)
}

free_graph_rcpp <- function(graphid) {
    invisible(.Call('_fastnetworklib_free_graph_rcpp', PACKAGE = 'fastnetworklib', graphid))
}

free_all_graphs_rcpp <- function() {
    invisible(.Call('_fastnetworklib_free_all_graphs_rcpp', PACKAGE = 'fastnetworklib'))
}

stats_rcpp <- function(graphid) {
    .Call('_fastnetworklib_stats_rcpp', PACKAGE = 'fastnetworklib', graphid)
}

connected_components_rcpp <- function(graphid) {
    .Call('_fastnetworklib_connected_components_rcpp', PACKAGE = 'fastnetworklib', graphid)
}

get_edgelist_rcpp <- function(graphid) {
    .Call('_fastnetworklib_get_edgelist_rcpp', PACKAGE = 'fastnetworklib', graphid)
}

generate_poisson_rcpp <- function(nvertices, mean_degree, seed) {
    .Call('_fastnetworklib_generate_poisson_rcpp', PACKAGE = 'fastnetworklib', nvertices, mean_degree, seed)
}

localised_random_walk_rcpp <- function(graphid, values, weights, alpha, nstep_max, precision, nthreads, normalise) {
    .Call('_fastnetworklib_localised_random_walk_rcpp', PACKAGE = 'fastnetworklib', graphid, values, weights, alpha, nstep_max, precision, nthreads, normalise)
}

write_pajek_rcpp <- function(graphid, filename) {
    invisible(.Call('_fastnetworklib_write_pajek_rcpp', PACKAGE = 'fastnetworklib', graphid, filename))
}

read_pajek_rcpp <- function(filename) {
    .Call('_fastnetworklib_read_pajek_rcpp', PACKAGE = 'fastnetworklib', filename)
}

decompose_exposure_rcpp <- function(graphid, values, exposure, weights, alpha) {
    .Call('_fastnetworklib_decompose_exposure_rcpp', PACKAGE = 'fastnetworklib', graphid, values, exposure, weights, alpha)
}

